// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this project by running a re-run of `flutterfire configure`',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY', // Nahraďte kľúčom z Firebase konzoly
    appId: '1:709796458721:web:840af4dc4277f05b9c07a0',
    messagingSenderId: '709796458721',
    projectId: 'parentfyapp',
    authDomain: 'parentfyapp.firebaseapp.com',
    storageBucket: 'parentfyapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY', // Nahraďte kľúčom z Firebase konzoly
    appId: '1:709796458721:android:04825dc6ca604ea99c07a0',
    messagingSenderId: '709796458721',
    projectId: 'parentfyapp',
    storageBucket: 'parentfyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // Nahraďte kľúčom z Firebase konzoly
    appId: '1:709796458721:ios:50859dab207bbf179c07a0',
    messagingSenderId: '709796458721',
    projectId: 'parentfyapp',
    storageBucket: 'parentfyapp.appspot.com',
    iosBundleId: 'com.example.parentFyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY', // Nahraďte kľúčom z Firebase konzoly
    appId: '1:709796458721:ios:50859dab207bbf179c07a0',
    messagingSenderId: '709796458721',
    projectId: 'parentfyapp',
    storageBucket: 'parentfyapp.appspot.com',
    iosBundleId: 'com.example.parentFyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY', // Nahraďte kľúčom z Firebase konzoly
    appId: '1:709796458721:web:74a6675c9d9558b49c07a0',
    messagingSenderId: '709796458721',
    projectId: 'parentfyapp',
    authDomain: 'parentfyapp.firebaseapp.com',
    storageBucket: 'parentfyapp.appspot.com',
  );
}
```

3.  **Dôležitý krok: Doplňte API kľúče**
    * Otvorte si váš [Firebase projekt](https://console.firebase.google.com/).
    * Kliknite na ikonu ozubeného kolesa -> **Project settings**.
    * V sekcii "Your apps" nájdite svoju **Android aplikáciu** a skopírujte si jej **`apiKey`**. Vložte ho do kódu vyššie namiesto `YOUR_ANDROID_API_KEY`.
    * Urobte to isté pre **Web aplikáciu** (`YOUR_WEB_API_KEY`) a ostatné.

4.  **Finálne príkazy:**
    Teraz, keď je všetko prepojené manuálne, spustite v termináli tieto príkazy:
    ```bash
    flutter clean
    flutter pub get
    flutter build apk
    
